# Generated by Django 2.2.5 on 2019-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_music', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=50)),
                ('genero_music', models.CharField(max_length=50)),
                ('link_music', models.CharField(max_length=255)),
            ],
        ),
    ]
